builders:
  luminix_builder:
    import: "package:luminix_generator/luminix_generator.dart"
    builder_factories: ["luminixBuilder"]
    build_extensions: {".json": [".dart"]}
    build_to: source
    auto_apply: dependents
    